### ISSUE TITLE
undefined: math.MaxInt with Go 1.16

### ISSUE THREAD

**Issue by friedemannf** [ericlagergren/decimal#171]
Recent changes have introduced the use of stdlib's math.MaxInt, see e.g. here:
https://github.com/ericlagergren/decimal/pull/167/files#diff-1ebe9d76178a47d079967d181e236d63579a3be7aa6596f39b1a013badbe1979R772

The new math constants have only been introduced in 1.17 and as of 1.16.9 aren't available in 1.16:
https://go-review.googlesource.com/c/go/+/247058/

Your go.mod states 1.16, leading to undescriptive errors when using decimal from 1.16. If I understood it correctly, increasing the go directive would lead to a reasonable error message, but would break your promise of supporting the the most recent major Go versions?

**Comment by ericlagergren** [comment]
Yep. Sorry about that. Thought the constant was older.

**Comment by ericlagergren** [comment]
@friedemannf please check that #172 works for you (I checked with the `go1.16.7` binary I had lying around).

**Comment by friedemannf** [comment]
@ericlagergren Thanks for your quick response!
Confirmed working with `go1.16.9`
```
❯ go version
go version go1.16.9 darwin/amd64
```

```
❯ go get github.com/ericlagergren/decimal
go: downloading github.com/ericlagergren/decimal v0.0.0-20211022110326-b30d25f2d547
# github.com/ericlagergren/decimal
../../go/pkg/mod/github.com/ericlagergren/decimal@v0.0.0-20211022110326-b30d25f2d547/big_ctx.go:772:27: undefined: math.MaxInt
../../go/pkg/mod/github.com/ericlagergren/decimal@v0.0.0-20211022110326-b30d25f2d547/big_ctx.go:3179:27: undefined: math.MaxInt
../../go/pkg/mod/github.com/ericlagergren/decimal@v0.0.0-20211022110326-b30d25f2d547/scan.go:312:16: undefined: math.MaxInt
```

```
❯ go get github.com/ericlagergren/decimal@b59ce5967ce2721644e1a771cd70d8d4b71a484c
go: downloading github.com/ericlagergren/decimal v0.0.0-20211026174116-b59ce5967ce2
go get: added github.com/ericlagergren/decimal v0.0.0-20211026174116-b59ce5967ce2
```
